---
title: "Your Title Here"
author: "Your Name"
date: "Date: `r Sys.Date()`"
output:
  html_document:
    theme: cosmo
    toc: true
    toc_float: true
    number_sections: true
    code_folding: show
---



Príklad 1: kopirka

```{r}
xi <- c(2448, 2482, 2485, 2489, 2506, 2514, 2516, 2533, 2553, 2586, 2590)
ni <- c(2,3,4,6,8,9,6,5,4,2,1)
p <- 0.95

arr <- rep(xi, times = ni)

smerodajna_odchylikla <- 30
bododh<- mean(arr)
bododh + c(-1, 1)* qnorm(p/2)/smerodajna_odchylikla/sqrt(length(arr))

library(EnvStats)


```

Príklad 2: Vápnik

```{r}
smerodajna_odchylka  <- 0.0012
priemer_vyberu  <- 0.3256
p <- 0.95 
alpha <- (1 - p) / 2
beta <- (1 + p) / 2

stredna_hodnota_odhad_chyby <- smerodajna_odchylka / sqrt(6)

z_lava <- qnorm(alpha)
z_prava <- qnorm(beta)

cislo_lave <- priemer_vyberu + z_lava * stredna_hodnota_odhad_chyby
cislo_prave <- priemer_vyberu + z_prava * stredna_hodnota_odhad_chyby

cislo_lave * 100
cislo_prave * 100


c_lave <- priemer_vyberu + z_lava * stredna_hodnota_odhad_chyby
c_lave * 100

c_prave <- priemer_vyberu + z_prava * stredna_hodnota_odhad_chyby
c_prave * 100

priemer_vyberu + c(-1, 1) * qnorm(p/2) * smerodajna_odchylka/sqrt(6)
priemer_vyberu 1 c(-1, 1) * qnorm(p/2) * smerodajna_odchylka/sqrt(6)
```

Príklad 3: Batéria

```{r}
battery_life <- c(272, 182, 274, 349, 240, 265, 204, 264, 255, 243, 245, 301, 260, 282, 223, 278, 211, 163, 253, 244, 233, 251, 254, 248, 248, 207, 252, 259, 230, 221)

# Basic statistics
mean_battery_life <- mean(battery_life)
median_battery_life <- median(battery_life)
std_deviation <- sd(battery_life)

varTest(battery_life, conf.level = .9)$conf.int
varTest(battery_life, conf.level = .9, alternative = "g")$conf.int
varTest(battery_life, conf.level = .9, alternative = "l")$conf.int
```

